### ISSUE TITLE
Ability to register adapter in-process

### ISSUE THREAD

**Issue by cancan101** [betodealmeida/shillelagh#181]
Add an ability to register a new adapter in-process, along the lines of how [sqlalchemy allows registering new dialect in-process](https://docs.sqlalchemy.org/en/14/core/connections.html#registering-dialects-in-process). Currently it looks like the only way to add an adapter to shillelagh is [through an entrypoint](https://github.com/betodealmeida/shillelagh/blob/6082939fd08145164edf9ac5c53c4dfc034eb070/src/shillelagh/backends/apsw/db.py#L506).

**Comment by betodealmeida** [comment]
Looks like it's possible to do it at runtime via `pkg_resources`: https://stackoverflow.com/a/48666503/807118

There's also a 3rd-party library that helps: https://prybar.readthedocs.io/en/stable/

But it might be easier to use a singleton for the registry as the source of truth, and populate it from `iter_entry_points`.
