### ISSUE TITLE
Don't log warning for "Couldn't load adapter" if adapter isn't specified

### ISSUE THREAD

**Issue by cancan101** [betodealmeida/shillelagh#194]
Currently I get a bunch of warnings like:
```
Couldn't load adapter datasetteapi = shillelagh.adapters.api.datasette:DatasetteAPI
```
even though I am explicitly passing in a list of adapters and not specifying that adapter.

These warnings should be printed only if the adapter is in the `adapters` list / there is no list:
https://github.com/betodealmeida/shillelagh/blob/a427de0b2d1ac27402d70b8a2ae69468f1f3dcad/src/shillelagh/backends/apsw/db.py#L510-L511

**Comment by betodealmeida** [comment]
Ah, good point!
