### ISSUE TITLE
SQLalchemy cascade delete-orphan does work

### ISSUE THREAD

**Issue by jimmymaise** [betodealmeida/shillelagh#206]
class Team(Base):
    __tablename__ = Constant.TEAM_SHEET
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String)
    members = relationship("TeamMember",
                           backref="team",
                           cascade="all, delete-orphan",
                           passive_deletes=True
                           )

class TeamMember(Base):
    __tablename__ = Constant.TEAM_MEMBER_SHEET
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(String)
    team_id = Column(String, ForeignKey(f'{Team.__tablename__}.id', ondelete="CASCADE"), nullable=False)
    # team = relationship("Team", backref=backref("members", cascade="all, delete-orphan"))

I try to use cascade delete but actually, it doesn't work. It just only deletes the record in the Team table.

_id = "ba2364ed-3e85-445a-9213-59ced7dac34a"
delete(Team).where(Team.id == _id)

shillelagh==1.0.10

**Comment by betodealmeida** [comment]
@jimmymaise, this works for me. Here's what I did:

I created a spreadsheet with 2 sheets (tabs), to hold the data: https://docs.google.com/spreadsheets/d/1KS6t27If4zbHiPJpT0D8viDiM2ccLH9w88ecL7XFEgs/edit#gid=0

I then ran this script, deleting one of the users ("bob"), and confirmed that the children (address) was also deleted:

```python
from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()

engine = create_engine(
    "gsheets://",
    subject="roberto@dealmeida.net",
    service_account_file="/Users/beto/Downloads/black-sanctum-314419-259b0d419a8f.json",
)


class User(Base):
    __tablename__ = "https://docs.google.com/spreadsheets/d/1KS6t27If4zbHiPJpT0D8viDiM2ccLH9w88ecL7XFEgs/edit#gid=0"

    id = Column(Integer, primary_key=True)
    name = Column(String(30))
    fullname = Column(String)

    addresses = relationship(
        "Address", back_populates="user", cascade="all, delete-orphan"
    )

    def __repr__(self):
        return f"User(id={self.id!r}, name={self.name!r}, fullname={self.fullname!r})"


class Address(Base):
    __tablename__ = "https://docs.google.com/spreadsheets/d/1KS6t27If4zbHiPJpT0D8viDiM2ccLH9w88ecL7XFEgs/edit#gid=1044942969"

    id = Column(Integer, primary_key=True)
    email_address = Column(String, nullable=False)
    user_id = Column(
        Integer,
        ForeignKey(User.id),
        nullable=False,
    )

    user = relationship(User, back_populates="addresses", foreign_keys=[user_id])

    def __repr__(self):
        return f"Address(id={self.id!r}, email_address={self.email_address!r})"


with Session(engine) as session:
    for user in session.query(User):
        print(user)
        print(user.addresses)

    bob = session.query(User).filter_by(name="bob").one()
    session.delete(bob)
    session.commit()
```
