### ISSUE TITLE
Polymorphic Fields

### ISSUE THREAD

**Issue by cancan101** [betodealmeida/shillelagh#211]
I wanted to know if is possible to write / use a polymorphic field (ie where the type can be variable, such as `int` _or_ `str`). As of now, they "just work", however from a typing standpoint this is wrong. Ie I can use the `String` field to handle something that comes from the API as either `str` or `int`, and downstream the type is preserved, however If I wanted to write the field, I cannot right now:

```python
class IntegerOtString(Field[Union[int, str], Union[int, str]]):
   pass
```
this fails mypy with:
```
error: Invalid type argument value for "Field"
```

The error itself can be fixed by changing the `TypeVar` for external to:
```python
External = TypeVar(
    "External",
    bound=Union[float,
    int,
    str,
    bool,
    datetime.date,
    datetime.datetime,
    datetime.time,
    datetime.timedelta,
    bytes,],
)
```
and fixing https://github.com/betodealmeida/shillelagh/issues/208

However it isn't clear what `type` and `db_api_type` should then be set to. I get there might be limitations due to pep 249, but I wonder if types can be relaxed a bit.

**Comment by betodealmeida** [comment]
This is super interesting! I think setting `type` to `TEXT` and `db_api_type` to `STRING` makes sense. The DB API 2.0 types don't make a lot of sense, and SQLite doesn't really care about types.
