### ISSUE TITLE
Support for Limit / Offset Constaints

### ISSUE THREAD

**Issue by cancan101** [betodealmeida/shillelagh#223]
https://www.sqlite.org/c3ref/c_index_constraint_eq.html, these were added in [3.38.0](http://www.hwaci.com/cgi-bin/sqlite/info/1e227ad9f413227f) and can be used to implement limit / offset on the backend.

One wrinkle is that these constrains do not have a left hand side, ie they are not applied to a specific column.

>The SQLITE_INDEX_CONSTRAINT_LIMIT and SQLITE_INDEX_CONSTRAINT_OFFSET operators have no left-hand operand, and so for those operators the corresponding aConstraint[].iColumn is meaningless and should not be used.

the `bounds` passed to `get_rows` might need a special value, like`*` to represent this.

**Comment by betodealmeida** [comment]
@cancan101 I implemented this, but decided to pass `limit` and `offset` explicitly to adapters that support it, instead of having it inside `bounds`:

https://github.com/betodealmeida/shillelagh/blob/06398926b22bf518e615a6063654f4049a3945ad/src/shillelagh/backends/apsw/vt.py#L487-L494
