### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by polvoazul** [betodealmeida/shillelagh#23]
Some docs would be nice. Showing how to use sqlalchemy dialects & dbapi, with, say, google sheets.

At a minimum, putting examples (or a link to them) in the README

**Comment by betodealmeida** [comment]
Thanks for the feedback, @polvoazul! I have a few examples under https://github.com/betodealmeida/shillelagh/tree/main/examples, but I agree more docs are needed! Currently the docs focus more on creating a new adapter than using `shillelagh`. I'll work on it.

**Comment by betodealmeida** [comment]
https://github.com/betodealmeida/shillelagh/commit/a742eae13f5742ec752f23413450f546e79c7bf9
