### ISSUE TITLE
Didn't manage to apply query on public google spreadsheet

### ISSUE THREAD

**Issue by Renat2001** [betodealmeida/shillelagh#242]
Good day everyone! Currently I'm using shillelagh package to access my google spreadsheet. But I'm getting error:<br/>  `Unsupported table: https://docs.google.com/spreadsheets/d/1Z8rDIh5Xu1QbrMU7afdT3kQB-75uHXwZ76AVJhTDH4w/edit#gid=1732117799`. I'm leaving here link:[https://docs.google.com/spreadsheets/d/1Z8rDIh5Xu1QbrMU7afdT3kQB-75uHXwZ76AVJhTDH4w/edit#gid=1732117799](url), so you can see where is my mistake. 
Code I used:
```connection = connect(":memory:")
cursor = connection.cursor()
mydf = pd.read_csv('C:\\Users\\R.Abdrakhmanov\\Desktop\\diploma_at_drive\\data\\ways.csv')
SQL = """
    SELECT *
    FROM "https://docs.google.com/spreadsheets/d/1Z8rDIh5Xu1QbrMU7afdT3kQB-75uHXwZ76AVJhTDH4w/edit#gid=1732117799"
"""
rows = cursor.execute(SQL)```

**Comment by betodealmeida** [comment]
@Renat2001 what version are you using and how did you install it? It works fine for me

```
% shillelagh
sql> SELECT * FROM "https://docs.google.com/spreadsheets/d/1Z8rDIh5Xu1QbrMU7afdT3kQB-75uHXwZ76AVJhTDH4w/edit#gid=1732117799";
  id
----
   0
   1
   2
   3
   4
   5
   6
   7
   8
   9
  10
  11
  12
  13
  14
  15
  16
  17
  18
  19
  20
  21
  22
  23
  24
  25
  26
  27
sql>
```

Make sure you install `shillelagh` with the optional dependencies that are needed for GSheets:

```bsh
pip install "shillelagh[gsheetsapi]"
```

**Comment by Renat2001** [comment]
I have the latest version of `shillelagh`. But I haven't install dependencies for GSheets. Now I got the point. Thanks!
