### ISSUE TITLE
Unable to subscript a Cursor object

### ISSUE THREAD

**Issue by aidenmitchell** [betodealmeida/shillelagh#326]
Hi there! This is probably something simple I'm missing, but I can't see to find the solution.
I'm using `shillelagh` as a replacement for `gsheetsdb`, for context.

This works:
```python
rows = cursor.execute(f'SELECT * FROM "{sheet_url}"')
for row in rows:
    print(row)
```
```
('Expo Line', '01/25/2023', '13:41', None)
```

What I can't seem to do, which I could with `gsheetsdb`, is this:
```python
rows = cursor.execute(f'SELECT * FROM "{sheet_url}"')
date = rows[0].Date
```

I get `TypeError: 'Cursor' object is not subscriptable`

Is there a way to get rows via index? Thank you!

**Comment by betodealmeida** [comment]
@aidenmitchell `Cursor.execute` returns a reference to the `Cursor` object itself:

https://github.com/betodealmeida/shillelagh/blob/7281a19cf66cb415a3b622edd59650e8d2a28055/src/shillelagh/backends/apsw/db.py#L245

If you want access to the first row you can either do:

```python
rows = cursor.execute(f'SELECT * FROM "{sheet_url}"').fetchall()
date = rows[0].Date
```

Or

```python
first_row = cursor.execute(f'SELECT * FROM "{sheet_url}"').fetchone()
data = first_row.Data
```
