### ISSUE TITLE
s3selectapi: An error occurred (AccessDenied) when calling the SelectObjectContent operation

### ISSUE THREAD

**Issue by mdeshmu** [betodealmeida/shillelagh#328]
**Describe the bug**
Access denied error even though correct permissions are granted

**To Reproduce**
1. pip install 'shillelagh[s3selectapi]' on Apache Superset instance
2. Set superset Database Settings as follows:
SQLALCHEMY URI: shillelagh+safe://
ENGINE PARAMETERS: {"adapters":["s3selectapi"]}
3. Go to SQL Lab and Query the S3 bucket. 
4. See error: shillelagh error: An error occurred (AccessDenied) when calling the SelectObjectContent operation: Access Denied

**Expected behavior**
data should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/57723564/216528268-c5ed46e4-f18d-42c3-83c9-f05f71838d51.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome 109.0.5414.75
 - Shillelagh 1.1.5

**Additional context**
Superset is hosted on AWS ECS and ECS task role has been given following S3 permissions on required bucket.
s3:GetBucketLocation
s3:GetObject
s3:ListBucket
My understanding is the Shillelagh will take credentials from ECS environment.

**Comment by betodealmeida** [comment]
>  My understanding is the Shillelagh will take credentials from ECS environment.

That is a great assumption and makes total sense, but unfortunately right now the credentials need to be explicitly passed:

```json
{
  "connect_args": {
    "adapters": ["s3selectapi"],
    "adapter_kwargs": {
      "s3selectapi": {
        "aws_access_key_id": "XXX",
        "aws_secret_access_key": "YYY"
      }
    }
  }
}
```

I'll create a ticket to have it read from the environment, if available.

**Comment by betodealmeida** [comment]
@mdeshmu can you give 1.2.0 a try? It should work now.

**Comment by mdeshmu** [comment]
@betodealmeida I have tested this with 1.2.0. It is able to take credentials from environment now. Thank you so much.

**Comment by mdeshmu** [comment]
@betodealmeida I have tested this with 1.2.0. It is able to take credentials from environment now. Thank you so much.
