### ISSUE TITLE
How can i query json data from API with authentication jwt token

### ISSUE THREAD

**Issue by vitmuathu** [betodealmeida/shillelagh#335]
Hi, i have a problem with my project using Shillelagh

My RestAPI return Json data need a jwt token in header, so how can i add jwt token to get data from api.

**Comment by betodealmeida** [comment]
Right now this is not supported, but it should be easy to add.

**Comment by betodealmeida** [comment]
@vitmuathu I added this feature to master, you can see the docs here: https://shillelagh.readthedocs.io/en/latest/adapters.html#generic-json-apis

**Comment by betodealmeida** [comment]
I should have a release out soon with this.
