### ISSUE TITLE
Always tries to load adapter datasetteapi

### ISSUE THREAD

**Issue by blackary** [betodealmeida/shillelagh#341]
**Describe the bug**
Whenever I try to use the connect method, it fails unless I've installed datasette

**To Reproduce**
1. `pip install shillelagh`
2. `from shillelagh.backends.apsw.db import connect`
3. `connect(":memory:")`
4. See error `Couldn't load adapter datasetteapi`

**Expected behavior**

No error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS

**Smartphone (please complete the following information):**

**Additional context**

`list(iter_entry_points("shillelagh.adapter"))` ->  
```
[EntryPoint.parse('csvfile = shillelagh.adapters.file.csvfile:CSVFile'),
 EntryPoint.parse('datasetteapi = shillelagh.adapters.api.datasette:DatasetteAPI'),
 EntryPoint.parse('genericjsonapi = shillelagh.adapters.api.generic_json:GenericJSONAPI'),
 EntryPoint.parse('githubapi = shillelagh.adapters.api.github:GitHubAPI'),
 EntryPoint.parse('gsheetsapi = shillelagh.adapters.api.gsheets.adapter:GSheetsAPI'),
 EntryPoint.parse('htmltableapi = shillelagh.adapters.api.html_table:HTMLTableAPI'),
 EntryPoint.parse('pandasmemory = shillelagh.adapters.memory.pandas:PandasMemory'),
 EntryPoint.parse('s3selectapi = shillelagh.adapters.api.s3select:S3SelectAPI'),
 EntryPoint.parse('socrataapi = shillelagh.adapters.api.socrata:SocrataAPI'),
 EntryPoint.parse('systemapi = shillelagh.adapters.api.system:SystemAPI'),
 EntryPoint.parse('weatherapi = shillelagh.adapters.api.weatherapi:WeatherAPI')]
 ```

**Comment by blackary** [comment]
@saurshaz-amplicomm That works fine, but should not be necessary. I should not have to install all of the adapters just to use any one of them.

**Comment by betodealmeida** [comment]
This is now fixed in `main`, I'll make a release soon.

**Comment by blackary** [comment]
@betodealmeida I can confirm that this is now fixed, however it still seems to try to connect to all of the connectors, and prints the output -- is it possible to hide all the failed "couldn't load *" commands?

```
Couldn't load adapter datasetteapi
Couldn't load adapter genericjsonapi
Couldn't load adapter githubapi
Couldn't load adapter htmltableapi
Couldn't load adapter pandasmemory
Couldn't load adapter s3selectapi
Couldn't load adapter socrataapi
Couldn't load adapter systemapi
Couldn't load adapter weatherapi
```

**Comment by betodealmeida** [comment]
@blackary yeah, let me fix it... I'll log the warning only for adapters that were explicitly specified.

**Comment by betodealmeida** [comment]
https://github.com/betodealmeida/shillelagh/pull/360/ should fix it.
