### ISSUE TITLE
Generic adapter for S3-compatible storage

### ISSUE THREAD

**Issue by goto-loop** [betodealmeida/shillelagh#342]
**Is your feature request related to a problem? Please describe.**
Currently only Amazon S3 is supported, but to access a self-hosted S3-compatible object storage (e.g. [MinIO](https://min.io/)) you need to implement a custom adapter.

**Describe the solution you'd like**
It would be great if you could simply point the existing S3 adapter to your own S3-compatible instance. `boto3.client()` supports this via the `endpoint_url` parameter.

**Describe alternatives you've considered**
Maybe a separate adapter that inherits from `S3SelectAPI` and overwrites only the necessary methods?

**Comment by betodealmeida** [comment]
This is a great idea, we should support passing `endpoint_url` to the adapter via the connection arguments (and maybe other parameters).
