### ISSUE TITLE
how to use filter When superset + shillelagh to get data from api

### ISSUE THREAD

**Issue by j491424570** [betodealmeida/shillelagh#363]
I installed shillelagh on superset to get data from api
I am running weatherapi demo and datasettes demo which works fine
but filter function seemed not working. How to make superset filter working?
Any suggestions are welcome

SQL on superset:
SELECT * FROM "https://san-francisco.datasettes.com/sf-trees/Street_Tree_List" LIMIT 5
![filter1](https://github.com/betodealmeida/shillelagh/assets/13111464/9e134760-0c81-4bef-ae1c-e31f96529dc1)
![filter not working](https://github.com/betodealmeida/shillelagh/assets/13111464/c264c497-de1b-4de0-af08-333aa16247ee)

**Comment by betodealmeida** [comment]
@j491424570 can you share the query that Superset is generating? In the chart builder you can click on the triple dots in the top right (near the "save" button), and see the query.

**Comment by betodealmeida** [comment]
Did you click "update chart" after adding the filter? I think that could be the problem.

It's working fine for me:

![Screenshot 2023-05-23 at 16-15-38 Preset](https://github.com/betodealmeida/shillelagh/assets/1534870/14d85393-e901-4d2d-8dfa-16b0bbaf5d83)

**Comment by betodealmeida** [comment]
Closing, feel free to reopen if the problem happens again.
