### ISSUE TITLE
pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by cancan101** [betodealmeida/shillelagh#370]
```
shillelagh/functions.py:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources
```
from https://setuptools.pypa.io/en/latest/pkg_resources.html:
>Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.

**Comment by cwegener** [comment]
I just started some work on this in apache/superset

I'm happy to do some janitorial work here as well.

**Comment by cwegener** [comment]
@cancan101 The deprecation warnings should disappear with this change: #371
