### ISSUE TITLE
Update `dbapi` method to `import_dbapi` for `APSWGSheetsDialect` to remove warning at the start of program

### ISSUE THREAD

**Issue by AndrewFucher** [betodealmeida/shillelagh#387]
**Is your feature request related to a problem? Please describe.**
For newer versions of SQLAlchemy (2.0), usage of `dbapi()` class method is deprecated. It is recommended to implement `import_dbapi()` class method. [Docs](https://docs.sqlalchemy.org/en/20/core/internals.html#sqlalchemy.engine.Dialect.import_dbapi)
So, the following warning is shown every time I use SQLAlchemy with Google Sheets adapter:
```
SADeprecationWarning: The dbapi() class method on dialect classes has been renamed to import_dbapi().  Implement an import_dbapi() class method directly on class <class 'shillelagh.backends.apsw.dialects.gsheets.APSWGSheetsDialect'> to remove this warning; the old .dbapi() class method may be maintained for backward compatibility.
```

**Describe the solution you'd like**
I would like to update the base class `APSWDialect`. Remove (if it does not break anything, I am not sure how it really works rn) or extend the class with the class method `import_dbapi`.

**Describe alternatives you've considered**
Leaving as it is for now. But as it is deprecated, better follow the docs.

**Additional context**
Python 3.11
SQLAlchemy==2.0.20
importlib-metadata==6.8.0 (without it SQLAlchemy, ORM to be exact, does not work)

**Comment by betodealmeida** [comment]
@AndrewFucher do you want to write a PR? All you need to do is add:

```python
import_dbapi = db
```

Here: https://github.com/betodealmeida/shillelagh/blob/cd2c6b1859eef3a6929edddc9305ab15992cc028/src/shillelagh/backends/apsw/dialects/base.py#L61

**Comment by betodealmeida** [comment]
Added in https://github.com/betodealmeida/shillelagh/pull/452.
