### ISSUE TITLE
How to configure the connection in Apache Superset to use Pandas data through Shillelagh?

### ISSUE THREAD

**Issue by ernestomccormick** [betodealmeida/shillelagh#388]
**Is your feature request related to a problem? Please describe.**

I haven't found documentation that helps me to create a connection to a Pandas dataframe using Shillelagh.

**Describe the solution you'd like**

I would like to have documentation and if possible a simple example to accomplish this setup.

**Describe alternatives you've considered**

I am lost 100%

**Additional context**

 This example is not clear enough:
https://images.ctfassets.net/ykljvmtfxwdz/473LkbIao4zdjBV8AZowX8/dfa430403da5e88415412825c2fbf077/Screenshot_2022-12-05_at_21-10-35_Preset.png

I would like to connect a Superset in a Docker container to a Pandas data frame in its Linux Host.  The idea is to create operational report that uses information available exclusively through a XMLRPC API.

**Comment by betodealmeida** [comment]
I think the best solution here is to write a custom adapter, since you need to do XMLRPC calls to create the dataframes.

(Discussed this on the Apache Superset Slack.)
