### ISSUE TITLE
Unable to create chart with gsheet as db connection although able to execute sql query on sql lab

### ISSUE THREAD

**Issue by aarfah-a** [betodealmeida/shillelagh#390]
**Describe the bug**
Unable to create chart with gsheet as db connection although able to execute sql query on sql lab
**To Reproduce**
1. Go to - Added gsheets:// as db connection after adding below lines in requirements-local.txt
```
shillelagh[gsheetsapi]
gsheetsdb
```
3. Click on - Create db connection as Add db -> Other -> url - gsheets:// -> Connect. Database successfulyy connected. Opened Sql lab -> Executed query: _`SELECT * from "https://docs.google.com/spreadsheets/d/1tWnaiMdLbzFhvkbAodS3GcO5r8_jxVqOzPbe1ylQRUw/edit?usp=sharing"`_

4. Scroll down to - Now saved the above query as dataset -> Create chart -> Got error -> `Unexpected Error: no such table: https://docs.google.com/spreadsheets/d/1tWnaiMdLbzFhvkbAodS3GcO5r8_jxVqOzPbe1ylQRUw/edit?usp=sharing`

5. See error

**Expected behavior**
Able to create charts and visualize the data from google sheets
**Screenshots**
<img width="1510" alt="image" src="https://github.com/betodealmeida/shillelagh/assets/148538187/bf72e0b2-aaab-46a9-bd69-497a8d8d9aad">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Using superset in docker and added the gsheet integration

**Comment by betodealmeida** [comment]
@aarfah-a do you know what version of shillelagh you're running? You can get it with this query:

```sql
SELECT VERSION();
```

Do you have access to the Superset logs, and if so, can you share them?

**Comment by aarfah-a** [comment]
Tried to uninstall and then installed the packages again. Restarted the docker container and then it worked. Thank you!
