### ISSUE TITLE
Google Sheet Adapter : Date Format throws "InvalidValue".

### ISSUE THREAD

**Issue by sebint** [betodealmeida/shillelagh#455]
**Describe the bug**
I have data containing date in a google sheets where the format is "1/2/24 14:41"(Month/Day/Year Hour(24):Minutes). and when the data get parsed its throwing InvalidValue('1/2/24 14:41').

So I changed the format to "02/01/2024 14:41:36", but it still thew the same error "InvalidValue('/01/2024 14:41:36')" but now the date is missing.

![Screenshot 2024-06-23 203953](https://github.com/betodealmeida/shillelagh/assets/15358561/b5046a22-aaf2-462d-b388-72273d47d675)

**Environment**
Python 3.11.9
Shillelagh 1.2.18

**Comment by betodealmeida** [comment]
@sebint can you share the spreadsheet with me (ralmeida@gmail.com)? Or a version with just the affected column, if the data is sensitive?

**Comment by sebint** [comment]
@betodealmeida, I have shared the spreadsheet with the given email address.

**Comment by betodealmeida** [comment]
Ah, this is similar to https://github.com/betodealmeida/shillelagh/issues/160.

Google API is returning for the column:

```python
{'id': 'A', 'label': 'Send time', 'type': 'timeofday', 'pattern': 'M/D/YY h:mm'}
```

Even though the value is `1/2/24 14:41` the type is `timeofday`. We have a function `infer_column_type` to fix problems like this, I'll make it handle this case as well (it only works with timestamps currently).

**Comment by betodealmeida** [comment]
@sebint I'll make a release with the fix today!

**Comment by betodealmeida** [comment]
@sebint 1.2.21 is out with the fix.
